services:
  db:
    image: neo4j:5.18
    container_name: fed-reg-devc-db
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - fed-reg-devc-db-data:/data
      - fed-reg-devc-db-logs:/logs
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]

  base:
    build:
      context: ./..
      dockerfile: ./dockerfiles/Dockerfile.devc
    container_name: fed-reg-devc-base
    volumes:
      - ..:/workspace:cached
    environment:
      - NEO4J_SERVER=fed-reg-devc-db
    command: sleep infinity

volumes:
  fed-reg-devc-db-data:
  fed-reg-devc-db-logs:
